sudo: false

language: php

php:
- 7.1

env:
  global:
  - DB_HOST=127.0.0.1
  - DB_NAME=personalsite_test
  - DB_USER=travis
  - DB_PASS=
  - DB_PORT=3306
  - DB_DRIVER=mysql

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE personalsite_test;'
  - php bin/console db:migrate
  - php bin/console seed:run

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs

after_success:
  - vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: 10b7f24f2c45b1350f5adccd6dd33bc5b3b65f944f699536981d65856cca435f
