sudo: false

language: php

php:
  - 7.1

before_script:
  - composer install -n
  - mysql -e 'CREATE DATABASE personalsite_test;'
  - php bin/console db:migrate

script:
  - phpunit
  - phpcs

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=personalsite_test
    - DB_USER=root
    - DB_PASS=
    - DB_PORT=3306
    - DB_DRIVER=mysql