sudo: false

language: php

php:
- 7.1

env:
  global:
  - DB_HOST=127.0.0.1
  - DB_NAME=personalsite_test
  - DB_USER=travis
  - DB_PASS=
  - DB_PORT=3306
  - DB_DRIVER=mysql

before_script:
- composer install
- mysql -e 'CREATE DATABASE personalsite_test;'
- php bin/console db:migrate
- php bin/console seed:run

script:
- vendor/bin/phpunit
- vendor/bin/phpcs
- vendor/bin/test-reporter

notifications:
  slack:
    secure: BkTdIAkknV9NktZlBwzezDg1iDl9RNvT89QT40VAWNNfxqd8tP9NWbRdJJA5+pdyt7SRvmiTIko5J9zAc6DmE4UgYZjo7qtekbedz0yWNnw/0I3ZEIvP1Fp+KZxcGtjEjfx4vkL6aPHA83TvPYAUtT+QS8DblJV3dxpBc2MeeMyhnpFpqbrv3KfMrG1I0iA7xbhJNnut9QLFN6DrZc5oijaqIB0a7g38u8HH4QYk15iSNtAOlHCl4vQ+2Jm9I2KY56/swntZjYwb0E5B2j4HORTC+zop8Kh7qvXF+R9pWneHOT0eHl0aRc69JgqHviIjHvEGzV402YYPHRBTYOOHDK+5CXq3j13DgFk/iMg13OAPXeC3www0/I5ioM/gXlrSoZmHmBJqq8hicvYbsiCs/LJDC8RKOaFKkFKclaooJR4KvPSQVomMBU75HlF/ouFma4Bp+UWP3ZpMzBILKAhcEuL0pPSClNbDa5wEOo5nlMeI4gbM+hDN41BhfcqscojLodis0WsVu3AECu8Zk16imocm1ePgQ56o9AJqZ9bCa07uSR6EJaDwdkrNHzA9bwCq89KIhFSJzL6kKFkIpTOlTaK1655RBIGGN7+t69aQ90NAK7wTOQu1H85+saDe7oumwoY6zvasGdZCtdVkyfjhp5iAHkxGL7ATJYn6eLykvZM=

addons:
  code_climate:
    repo_token:
      secure: 0jGQjf3xji9VQyKpan182zoknI3MIozRdo/CfVNaJ0tLLnDGSAVZAq3ujhxHzlbuDSUIESpyPtdl3yiuka61ydRMkM/NzH/s7qXbmSKvjNCUVl7E0uRsrHFtMXq4CKsRJ5QxZMzKJ47XUjSL2OQVXQI4f/LkupU6t4nkKoqcptxHxWJOqC1SQy4QDRCc96YUb8SzHQaiJCMdQDmgBnbQHVPhvQGy3SZI4/PJ8z18N9wIuabnRYaWFQLt+Jwfa2bcSmRFwIDyMQBBp7mTo7diDwDF8a5tzwpVOmCwHhxy2HL4Db6VTDVBQ1TF7nLrc0rzwtOUkaNmQK407Xaoi7bw05fTP+jo1JqYhlhY2sKc3N+p4JkOYi3fnlpQwx364XKn3dYFoX5wkGYwoCClyOKKgCXKy+zAFZhLvVMNo/5wg7eWRssl/7/ST9EiuXNxaTsnBpIjNzkokE9USsaOmi5T3qn6U8PgLNdEdC+8c0jbSQYnmSd7nQVo9YH9r+BmW6TmP/fXlR2Sdh3DeiU0QYNMGF9ijqomCYPPiIIW6O7gy8ilQPXmE/NT1Njcz4yAf2pAQX4q96/FX9Cxtdvc7qqvls6gOAXHPASwQW06IyQpbSvhHgvY5thG7Ez6PlisdFkw3qnSU5mEluIX45661iZdu5etex2Ih3aygqMOWdi1aog=