sudo: false

language: php

php:
  - 7.1

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=personalsite_test
    - DB_USER=root
    - DB_PASS=
    - DB_PORT=3306
    - DB_DRIVER=mysql

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE personalsite_test;'
  - php bin/console db:migrate
  - mysql -u root personalsite_test < tests/personalsite_test_2017-01-17.sql

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
